version: '3.7'
services:
  wgc-server:
    # build an image named wgc-server
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    image: wgc-server-img
    container_name: wgc-server
    # run command, nodemon for hot reloading
    command: npx nodemon index.js
    # volumes to mount
    volumes:
      - type: bind
        source: ./server
        target: /usr/app/server
        volume:
          nocopy: true
      - type: bind
        source: ./server/node_modules
        target: /usr/app/server/node_modules
        volume:
          nocopy: true
    # port mapping
    ports:
      - '5000:5000'
    env_file: .env
    networks:
      - app-network
    restart: always

  wgc-client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    image: wgc-client-img
    stdin_open: true
    tty: true
    container_name: wgc-client
    command: npm start
    volumes:
      - type: bind
        source: ./client
        target: /usr/app/client
      - type: bind
        source: ./client/node_modules
        target: /usr/app/client/node_modules
    depends_on:
      - wgc-server
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
