version: "3.7"
services:
  server:
    image: {{wgc-server}}
    container_name: p-wgc-node-server
    ports:
      - "5000:5000"
    env_file: .env
    networks:
      - app-network
    restart: always

  client:
    image: {{wgc-client}}
    container_name: p-wgc-react-client
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
    app-network:
        driver: bridge