version: "3.7"
services:
  server:
    # build an image named wgc-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: p-wgc-server
    container_name: p-wgc-node-server
    # port mapping
    ports:
      - "5000:5000"
    env_file: .env
    networks:
      - app-network
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: p-wgc-client
    container_name: p-wgc-react-client
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
    app-network:
        driver: bridge