name: Deploy to Heroku Production Environment

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          branch: release
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ''
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
      - run: heroku container:login
      - run: heroku container:push web --app ${{ secrets.HEROKU_PRD_APP }}
      - run: heroku container:release web --app ${{ secrets.HEROKU_PRD_APP }}
