name: Deploy to Heroku Staging Environment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          branch: master
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STG_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: ${{ secrets.STG_APP_URL }}
          delay: 10
          usedocker: true
          dontuseforce: true
        env:
          HD_NODE_ENV: production
          HD_USER: ${{ secrets.USER }}
          HD_PASS: ${{ secrets.PASS }}
